### PR TITLE
Update whats_new for a new release

### PR DESCRIPTION
**Pull request by alexgleith**
### Reason for this pull request

* Prepare for a new release of Datacube

### Proposed changes

- Update whats_new

 - [x] Fully documented, including `docs/about/whats_new.rst` for all changes

### CODE REVIEW

**Review by robbibt — APPROVED** [review]

**Comment by robbibt** [comment]
One question: now that searching for multiple products is "officially" supported in ODC, should we update the `dc.load` "product" param docstring to mention this? Currently it's effectively an undocumented feature

**Comment by alexgleith** [comment]
> One question: now that searching for multiple products is "officially" supported in ODC, should we update the `dc.load` "product" param docstring to mention this? Currently it's effectively an undocumented feature

I think this is best done using Typing, but there's not a lot of typing in there now.

I'm inclined to leave it as undocumented for now... is that bad?

**Review by SpacemanPaul — APPROVED** [review]
Great to see the release pace picking up.

**Comment by robbibt** [comment]
> > One question: now that searching for multiple products is "officially" supported in ODC, should we update the `dc.load` "product" param docstring to mention this? Currently it's effectively an undocumented feature
> 
> I think this is best done using Typing, but there's not a lot of typing in there now.
> 
> I'm inclined to leave it as undocumented for now... is that bad?

I don't have strong feelings either way, just that leaving it undocumented was what led to this "bug" originally. We can always implement some docs changes down the track though

**Pull request merged**
