### PR TITLE
Documentation Fixes (Spelling/Typos/checker upgrade)

### PR DESCRIPTION
**Pull request by omad**
### Reason for this pull request

- Fixing silly spelling mistakes and typos.
- removing unused boilerplate from the CI doc checker
- Upgrading the version of the CI doc checker

Failing CI checks in another PR made me take a closer look at our CI documentation checks.

I don't think we want a spell checker running in CI. There's too much toil keeping it up to date, and, the one we have [doesn't support reStructuredText](https://github.com/facelessuser/pyspelling/issues/149), and isn't setup to be able to run locally, so has a massive commit/push/wait for CI cycle.

But, that can be a conversation.

----
📚 Documentation preview 📚: https://datacube-core--1659.org.readthedocs.build/en/1659/

### CODE REVIEW

**Review by caitlinadams — APPROVED** [review]
Thanks Damien, I appreciate you making those changes!

**Comment by caitlinadams** [comment]
I agree that it might be too much to have a spelling check running in CI. As an alternative proposal, perhaps we can have a VS Code dev container specifically for docs with a spell checker extension? I'm only just starting to understand/play with VS Code dev containers, so it might work, or it might not!

**Comment by omad** [comment]
> I agree that it might be too much to have a spelling check running in CI. As an alternative proposal, perhaps we can have a VS Code dev container specifically for docs with a spell checker extension? I'm only just starting to understand/play with VS Code dev containers, so it might work, or it might not!

It would definitely work! We don't have a dev container at all for now though...

**Comment by caitlinadams** [comment]
> It would definitely work! We don't have a dev container at all for now though...

One for the docs committee to-do list!

**Pull request merged**
