### PR TITLE
Add sentinel 2 COG product definitions and s3 indexing script

### PR DESCRIPTION
**Pull request by roarmstrong**
Add Sentinel 2 Granule and ARD product definitions and a Sentinel 2 COG on S3 indexing script to begin building directory structure similar to https://github.com/ceos-seo/agdc-v2/tree/master/ingest for product definitions, ingest and indexing scripts.

### CODE REVIEW

**Review by andrewdhicks — COMMENTED** [review]
Should GA-flavor products (NBAR, NBART) go in a DEA repo instead?

**Comment by mpaget** [comment]
Replying to @andrewdhicks: For index/ingest definitions and scripts I'd suggest erring on the side of openness (i.e., in odc github), for while they may be GA/DEA specific they will likely serve as good examples for others. However, as long as contribs can be found across repos it doesn't matter too much where they actually live. In the end its your call.

**Comment by roarmstrong** [comment]
@andrewdhicks Happy to move the GA product definitions, which repo would you suggest? And maybe a readme in the ingestion folder (and something in the docs) which tells people where they could find those product definitions?

**Comment by andrewdhicks** [comment]
@roarmstrong We have found that if we include product definitions in the ODC repo, there is an expectation from users that the product is available for all users and areas.  For this product, the GA/digitalearthau repo would be the appropriate place.

In terms of openness, the GA repo is public, and linked to from the current installation documents at https://www.opendatacube.org/data-preparation. There is an ongoing task to consolidate the product definitions, prepare scripts and product documentation into a central location (that clearly indicates what product is available from where), but this would also be outside of the datacube-core repo.

**Comment by omad** [comment]
For anyone looking for these Sentinel 2 product definitions and indexing scripts, see https://github.com/GeoscienceAustralia/digitalearthau/pull/105

**Pull request closed without merging**
