### PR TITLE
Tutorial and changes in functions to export to file

### PR DESCRIPTION
**Pull request by cronosnull**
First part of a small tutorial of data cube use (eng and spanish version).
Changes on analytics_utils to export to files

### CODE REVIEW

**Comment by woodcockr** [comment]
This is looking good to me. Could the other Approvers please cast their vote so we can process the PR?

I haven't had a chance to test this in my dev environment yet but the previous items I raised with the original PR have been addressed so once tested I'm +1 on this contribution.

**Comment by mjondrow-ama** [comment]
This looks good from my end.

**Comment by petewa** [comment]
This looks good, +1 from me.

**Comment by mpaget** [comment]
no problem as I can see

**Comment by woodcockr** [comment]
We have sufficient votes and the other Approvers are unable review at this time. PR merged.

**Pull request merged**
