### PR TITLE
The Python Modules Index in the Docs isn't working

### PR DESCRIPTION
**Pull request by omad**
### Expected behaviour
This page has a list of all the Python modules in Core https://datacube-core.readthedocs.io/en/latest/py-modindex.html

### Actual behaviour

It does not!

### CODE REVIEW

**Comment by omad** [comment]
It turns out `autodoc` isn't smart enough to insert Python module references automatically. When we switched to structuring API documentation by hand (not using `automodule` and not using `sphinx-apidoc`, we neglected to put in `.. py:module::` directives.

I'll go and put some in at appropriate places.

**Comment by omad** [comment]
After this change, that page will look like
image

There are some modules still not included like `drivers`, `ui` and `storage`, because they don't have useful sections in the docs.

**Review by alexgleith — COMMENTED** [review]
Looks good to me!

**Review by alexgleith — COMMENTED** [review]
lgtm

**Review by alexgleith — COMMENTED** [review]
Approved

**Comment by alexgleith** [comment]
Err, why won't it let me approve this.

**Comment by alexgleith** [comment]
Oh, I created the issue. Someone else needs to approve!

**Review by uchchwhash — APPROVED** [review]
💯

**Pull request merged**
