### PR TITLE
Merge ga/milestone1 work into develop branch

### PR DESCRIPTION
**Pull request by omad**
Future work can be developed on feature branches.

### CODE REVIEW

**Comment by simonaoliver** [comment]
Ok with me

**Comment by wenjunwu** [comment]
+1 from me.

## Geoscience Australia Disclaimer: This e-mail (and files transmitted with it) is intended only for the person or entity to which it is addressed. If you are not the intended recipient, then you have received this e-mail by mistake and any use, dissemination, forwarding, printing or copying of this e-mail and its file attachments is prohibited. The security of emails transmitted cannot be guaranteed; by forwarding or replying to this email, you acknowledge and accept these risks.

**Comment by simonaoliver** [comment]
Any objections / barriers to this happening now? That's 2 votes for.

**Comment by woodcockr** [comment]
I'll have to abstain on my vote. Just got back today and nothing in my environment is up to date.

**Comment by simonaoliver** [comment]
@petewa @mpaget ?

**Comment by mpaget** [comment]
Hard for me to reply constructively, sorry, as I’m not across any potential implications right now.
As far as I understand its ok to merge given that milestone1 is our most recent implementation, and given that I understand @petewahttps://github.com/petewa’s work is appropriately connected in.
I’ll nominate @petewahttps://github.com/petewa as the proxy for my vote – unless he doesn’t come online in time (later today?), in which case you can have a +1 from me.

**Comment by petewa** [comment]
I can't give a +1 on this pull request yet.

This pull request breaks with the database @andrewdhicks pointed me to when I was testing his xray-dask branch in December 2015. The new databases do not have any Landsat 5 data in them and the schema changed a fair bit.

Could you please point me to a database + storage units that works with this branch with Landsat 5 test data.

Edit: I spoke to @simonaoliver and we are sorting this out.

Will +1 it when I confirm the updated new API works with the AE/EE.

**Comment by jeremyh** [comment]
Thanks for the update Peter.

Note that most of us are running our own databases — mainly for flexibility and to avoid contention. It's fairly easy to (re)create a db; there are some pages on this in the [docs](http://agdc-v2.readthedocs.org/en/ga-milestone1/db_setup.html), although they are admittedly fairly sparse at the moment — I plan to expand and clean them up a little. 

We are also still expanding the core features, so there are further schema changes upcoming.

**Comment by petewa** [comment]
Thanks Jeremy, I took a copy of the demo database and data that Simon pointed me to and reproduced it on my local vm. I ran into a snag with api.get_data()

It seems to be returning mostly of identical values for each time slice, can someone more familiar with the data please confirm this is intended.

This is the query I'm executing:

data_request = {
    'platform': 'LANDSAT 5',
    'product': 'NBAR',
    'variables': ('band_30', 'band_40'),
    'dimensions': {
        'longitude': {
            'range': (150, 150.256),
        },
        'latitude': {
            'range': (-34.0, -33.744),
        }
    }
}

dapi = api.API()
data = dapi.get_data(data_request)

It looks like most of the time slices in data are identical, is this suppose to be like this?
All (lat, long) time slices are identical except for slice 1 which are all ndv's.
The shape of the data is (13, 1024, 1024). I tried a few other dimension ranges.

Regarding what you said about further schema changes, we should have a database + data that is in sync with the pull request. This would help contributors testing the pull request. This was not available until I spoke to Simon.

**Comment by simonaoliver** [comment]
Thanks Peter - integration of AE/EE now appears complete to a satisfactory level.

**Pull request merged**
