### PR TITLE
Add code of conduct

### PR DESCRIPTION
**Pull request by alexgleith**
### Reason for this pull request
Adding a code of conduct to the project based on readings [here](https://www.contributor-covenant.org/) and [here](https://opensource.guide/code-of-conduct/).

### Proposed changes

- Add code-of-conduct.md
- Link to if from the main readme

 - [x ] Fully documented, including `docs/about/whats_new.rst` for all changes

### CODE REVIEW

**Comment by alexgleith** [comment]
There's a question outstanding before we merge about who should be the conduct for reporting issues, see: https://opensource.guide/code-of-conduct/#deciding-how-youll-enforce-your-code-of-conduct. Who should it be?

**Comment by alexgleith** [comment]
So @andrewdhicks pointed out we have a bunch of words over here: https://github.com/opendatacube/governance/tree/master/conduct so this PR may be redundant. Or this one may supersede the one over there.

**Comment by alexgleith** [comment]
Hey @woodcockr, how would you feel about reviewing this. I think we should make it happen :-)

**Comment by woodcockr** [comment]
All members of the SC have been asked to review - its on the [actions list](https://github.com/opendatacube/datacube-core/wiki/ODC-SC-Meeting-2019-07-25).
It'll be on the agenda for decision at the next SC meeting which is next week

**Comment by alexgleith** [comment]
Hey @woodcockr, after the [SC meeting](https://github.com/opendatacube/datacube-core/wiki/ODC-SC-Meeting-2019-08-22) resolution today, I'm planning on merging this PR. Can you please review and approve so that I can do so 😄

**Review by woodcockr — APPROVED** [review]
Looks good.

**Pull request merged**
