### PR TITLE
Update coding style to be more in line with pep8 and pep257

### PR DESCRIPTION
**Pull request by omad**
This makes _mostly_ trivial changes to large portions of the code base, to bring the coding style more in line with python standards. Most of the refactoring was done automatically with PyCharm, but hasn't yet been extensively tested.

I've left some of the public method names with uppercase letters in them. Opinions welcome on whether we should change these too.

We need to adopt a coding style moving forwards, and earlier rather than later will be easier.

Changes include:
- 4 space indents instead of tabs
- Line lengths < 120
- Extracting methods to functions when they don't need to be part of a class
- Variables and method names `lowercase_with_underscores` instead of `CamelCase`
- Removing unused method parameters
- Organising imports

### CODE REVIEW

**Comment by woodcockr** [comment]
This looks fine to me and in line with the objective to be fully PEP8 compliant.
+1 support from me.

**Comment by wenjunwu** [comment]
+1 support from me

**Comment by simonaoliver** [comment]
Ok from me

**Comment by petewa** [comment]
+1 from me.

**Comment by woodcockr** [comment]
All done, thank you

**Pull request merged**
