### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by omad**
### Reason for this pull request
It's my understanding that the code in `datacube/ndexpr`, `datacube/execution` and `datacube/analytics` is not going to be developed further or supported into the future. That the plan is to work on new code implementing similar features.

If so, I'd like to propose removing this code in an attempt to start cleaning up the repository. The codebase is currently somewhat unapproachable, and we've had queries asking about these features, and how to use them. There's currently no useful documentation or support available.

### Proposed changes
- Removing the unsupported ndexpr, analytics and execution engine code

 - [x] Tests removed / passing
 - [x] Fully documented, including `docs/about/whats_new.rst` for all changes

### CODE REVIEW

**Comment by woodcockr** [comment]
@petewa and @rtaib have an execution engine branch with the new developments for this ongoing work.

How about we let CSIRO do this particular aspect of the tidy up and correctly include the new developments?

**Comment by Kirill888** [comment]
@woodcockr Code is a liability. If it's not being used it should be deleted. Have a look at this file for example:

https://github.com/opendatacube/datacube-core/commits/develop/datacube/analytics/analytics_engine.py

Last meaningful change in early 2016, after that just minor edits to keep it "running" even though it's not actually being used by anyone as far as I can tell. This is a lot effort expended for no gain. 

It is also confusing to new comers, they can't tell if this was abandoned or not. So if you want this code to remain in the code base please provide us with a clear plan and strategy for developing this further

- Who is going to be working on this and what proportion of the time they will dedicate to this work
- What new features you planning to deliver
- What is the timeline for new work

As it stands, this looks like dead weight that needs to be pruned, and I totally support @omad in deleting this.

**Review by Kirill888 — DISMISSED** [review]

**Comment by woodcockr** [comment]
@Kirill888 I see, I have stated we have a plan and that CSIRO would clean it up, and we have over several meetings of the ODC and in a variety of forums shown that plan for the EE and its strategy

The response is to ignore this and approve the changes and ignore our assistance.
Seems like a pretty poor response to me.

**Comment by Kirill888** [comment]
@woodcockr approve is not the same as merge. Do I approve of this pull request? Yes I do. Have we as a team decided to merge this change into develop? No we haven't yet, as we are waiting for original contributors, i.e. @petewa, to chime in.

**Comment by woodcockr** [comment]
@Kirill88 I am a very experienced software developer and manager, I understand the difference, another assumption made in error. There is no need to make this personal. I rejected the review comment because you stated it isn't being used, which it is and will be in the new version. I have corrected an inaccuracy and prevented github from allowing the merge request to occur so it isn't accidentally or otherwise merged by invalidating the approval. That is the function the dismiss button is intended to serve, that is all.
@petewa will shortly get to the review of this PR, and will no doubt approve it but for the correct reasons and the reviews will now show that and no longer propagate an error.

**Comment by woodcockr** [comment]
Should probably modify the whats_new.rst to point forward to the new developments coming online. In case there are others out there using this code we aren't aware of.

**Comment by petewa** [comment]
The code currently being discussed, is used in the current Algal Bloom monitoring application, which we are in the process of porting to v2 of this set of functionality (ndexpr, ae, ee).

The new functionality will be included via a new PR when ready, It in currently sitting in a branch 
csiro/execution-engine.

Having said that, we have completed enough of the port, that this can be deleted.

I agree with @woodcockr comment to "modify the whats_new.rst to point forward to the new developments coming online."

**Review by petewa — CHANGES_REQUESTED** [review]
Just need one change to docs/about/whats_new.rst to point to the new Execution Engine v2 coming soon in the csiro/execution-engine branch.

**Review by petewa — DISMISSED** [review]

**Review by petewa — APPROVED** [review]

**Pull request merged**
