### PR TITLE
Minor cli, location and dataset friendlieness improvements

### PR DESCRIPTION
**Pull request by jeremyh**
A few trivial but convenient cli/model changes after using them in the DEA scripts.

See the commit messages for justifications.

 - [X] Tests added / passed
 - [X] Fully documented, including `docs/about/whats_new.rst` for all changes

### CODE REVIEW

**Comment by jeremyh** [comment]
The Travis build failed in my repo during the last docs deploy step, which seems to be environmental and unrelated to the changes:

https://travis-ci.org/jeremyh/datacube-core/jobs/250182192
```
Deploying application
uploading "3.6/datacube-1.2.2+280.g142a5d1f.tar.gz" with {:content_type=>"application/gzip"}
/home/travis/.rvm/gems/ruby-2.2.6/gems/aws-sdk-core-2.10.7/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call': The request signature we calculated does not match the signature you provided. Check your key and signing method. (Aws::S3::Errors::SignatureDoesNotMatch)
	from /home/travis/.rvm/gems/ruby-2.2.6/gems/aws-sdk-core-2.10.7/lib/aws-sdk-core/plugins/s3_sse_cpk.rb:19:in `call'
	from /home/travis/.rvm/gems/ruby-2.2.6/gems/aws-sdk-core-2.10.7/lib/aws-sdk-core/plugins/s3_dualstack.rb:24:in `call'
	from /home/travis/.rvm/gems/ruby-2.2.6/gems/aws-sdk-core-2.10.7/lib/aws-sdk-core/plugins/s3_accelerate.rb:34:in `call'
	from /home/travis/.rvm/gems/ruby-2.2.6/gems/aws-sdk-core-2.10.7/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call'
	from /home/travis/.rvm/gems/ruby-2.2.6/gems/aws-sdk-core-2.10.7/lib/aws-sdk-core/plugins/idempotency_token.rb:18:in `call'
	from /home/travis/.rvm/gems/ruby-2.2.6/gems/aws-sdk-core-2.10.7/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
	from /home/travis/.rvm/gems/ruby-2.2.6/gems/aws-sdk-core-2.10.7/lib/seahorse/client/plugins/response_target.rb:21:in `call'
	from /home/travis/.rvm/gems/ruby-2.2.6/gems/aws-sdk-core-2.10.7/lib/seahorse/client/request.rb:70:in `send_request'
	from /home/travis/.rvm/gems/ruby-2.2.6/gems/aws-sdk-core-2.10.7/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
	from /home/travis/.rvm/gems/ruby-2.2.6/gems/aws-sdk-resources-2.10.7/lib/aws-sdk-resources/services/s3/file_uploader.rb:42:in `block in put_object'
	from /home/travis/.rvm/gems/ruby-2.2.6/gems/aws-sdk-resources-2.10.7/lib/aws-sdk-resources/services/s3/file_uploader.rb:49:in `open_file'
	from /home/travis/.rvm/gems/ruby-2.2.6/gems/aws-sdk-resources-2.10.7/lib/aws-sdk-resources/services/s3/file_uploader.rb:41:in `put_object'
	from /home/travis/.rvm/gems/ruby-2.2.6/gems/aws-sdk-resources-2.10.7/lib/aws-sdk-resources/services/s3/file_uploader.rb:34:in `upload'
	from /home/travis/.rvm/gems/ruby-2.2.6/gems/aws-sdk-resources-2.10.7/lib/aws-sdk-resources/services/s3/object.rb:252:in `upload_file'
	from /home/travis/.rvm/gems/ruby-2.2.6/gems/dpl-1.8.39/lib/dpl/provider/s3.rb:57:in `block (2 levels) in push_app'
	from /home/travis/.rvm/gems/ruby-2.2.6/gems/dpl-1.8.39/lib/dpl/provider/s3.rb:48:in `glob'
	from /home/travis/.rvm/gems/ruby-2.2.6/gems/dpl-1.8.39/lib/dpl/provider/s3.rb:48:in `block in push_app'
	from /home/travis/.rvm/gems/ruby-2.2.6/gems/dpl-1.8.39/lib/dpl/provider/s3.rb:47:in `chdir'
	from /home/travis/.rvm/gems/ruby-2.2.6/gems/dpl-1.8.39/lib/dpl/provider/s3.rb:47:in `push_app'
	from /home/travis/.rvm/gems/ruby-2.2.6/gems/dpl-1.8.39/lib/dpl/provider.rb:154:in `block in deploy'
	from /home/travis/.rvm/gems/ruby-2.2.6/gems/dpl-1.8.39/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-2.2.6/gems/dpl-1.8.39/lib/dpl/provider.rb:154:in `deploy'
	from /home/travis/.rvm/gems/ruby-2.2.6/gems/dpl-1.8.39/lib/dpl/provider/s3.rb:75:in `deploy'
	from /home/travis/.rvm/gems/ruby-2.2.6/gems/dpl-1.8.39/lib/dpl/cli.rb:32:in `run'
	from /home/travis/.rvm/gems/ruby-2.2.6/gems/dpl-1.8.39/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-2.2.6/gems/dpl-1.8.39/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.2.6/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-2.2.6/bin/dpl:23:in `<main>'
failed to deploy
```

**Comment by andrewdhicks** [comment]
The AWS keys for deployment are encrypted with settings on the opendatacube/datacube-core Travis project, so it should be ok.  Pull request builds don't trigger the deploy step, which is why it is working here.

**Comment by omad** [comment]
Let's better specify what to upload using `on:` in the `.travis.yaml`. See https://docs.travis-ci.com/user/deployment#Conditional-Releases-with-on%3A

**Review by omad — APPROVED** [review]
I've made a couple of small doc/readability updates. but otherwise looks good.

**Pull request merged**
