### PR TITLE
Update windows.rst

### PR DESCRIPTION
**Pull request by RichardScottOZ**
change from ADC to ODC in install

### Reason 

Edits

### CODE REVIEW

**Comment by RichardScottOZ** [comment]
Should there be conda instructions - or generally pip-installed?

Geospatial usual suspects much easier to install by the former, of course.

**Comment by RichardScottOZ** [comment]
Does it have to be python 3.6?

**Comment by RichardScottOZ** [comment]
python 3.8 install test on windows worked fine, anyway

**Review by uchchwhash — APPROVED** [review]
Thanks @RichardScottOZ!

**Pull request merged**
