### PR TITLE
fix reproject in virtual product

### LINKED ISSUE #1027: 'DatasetType' object has no attribute '_all_measurements' with dask
Hey all, I am receiving an error when using dask to perform some computations. Not sure entirely if this is an ODC/Dask/xarray issue though. Any help would be appreciated. The code example below was extracted from a jupyter notebook.

### Expected behaviour
Computed data and plot

### Actual behaviour

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-15-37a4078ad80d> in <module>
----> 1 resampled.compute().plot(size=10)

/opt/conda/envs/datacube/lib/python3.6/site-packages/xarray/core/dataarray.py in compute(self, **kwargs)
    832         """
    833         new = self.copy(deep=False)
--> 834         return new.load(**kwargs)
    835 
    836     def persist(self, **kwargs) -> "DataArray":

/opt/conda/envs/datacube/lib/python3.6/site-packages/xarray/core/dataarray.py in load(self, **kwargs)
    806         dask.array.compute
    807         """
--> 808         ds = self._to_temp_dataset().load(**kwargs)
    809         new = self._from_temp_dataset(ds)
    810         self._variable = new._variable

/opt/conda/envs/datacube/lib/python3.6/site-packages/xarray/core/dataset.py in load(self, **kwargs)
    652 
    653             # evaluate all the dask arrays simultaneously
--> 654             evaluated_data = da.compute(*lazy_data.values(), **kwargs)
    655 
    656             for k, data in zip(lazy_data, evaluated_data):

/opt/conda/envs/datacube/lib/python3.6/site-packages/dask/base.py in compute(*args, **kwargs)
    450         postcomputes.append(x.__dask_postcompute__())
    451 
--> 452     results = schedule(dsk, keys, **kwargs)
    453     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    454 

/opt/conda/envs/datacube/lib/python3.6/site-packages/distributed/client.py in get(self, dsk, keys, restrictions, loose_restrictions, resources, sync, asynchronous, direct, retries, priority, fifo_timeout, actors, **kwargs)
   2712                     should_rejoin = False
   2713             try:
-> 2714                 results = self.gather(packed, asynchronous=asynchronous, direct=direct)
   2715             finally:
   2716                 for f in futures.values():

/opt/conda/envs/datacube/lib/python3.6/site-packages/distributed/client.py in gather(self, futures, errors, direct, asynchronous)
   1991                 direct=direct,
   1992                 local_worker=local_worker,
-> 1993                 asynchronous=asynchronous,
   1994             )
   1995 

/opt/conda/envs/datacube/lib/python3.6/site-packages/distributed/client.py in sync(self, func, asynchronous, callback_timeout, *args, **kwargs)
    832         else:
    833             return sync(
--> 834                 self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
    835             )
    836 

/opt/conda/envs/datacube/lib/python3.6/site-packages/distributed/utils.py in sync(loop, func, callback_timeout, *args, **kwargs)
    337     if error[0]:
    338         typ, exc, tb = error[0]
--> 339         raise exc.with_traceback(tb)
    340     else:
    341         return result[0]

/opt/conda/envs/datacube/lib/python3.6/site-packages/distributed/utils.py in f()
    321             if callback_timeout is not None:
    322                 future = asyncio.wait_for(future, callback_timeout)
--> 323             result[0] = yield future
    324         except Exception as exc:
    325             error[0] = sys.exc_info()

/opt/conda/envs/datacube/lib/python3.6/site-packages/tornado/gen.py in run(self)
    733 
    734                     try:
--> 735                         value = future.result()
    736                     except Exception:
    737                         exc_info = sys.exc_info()

/opt/conda/envs/datacube/lib/python3.6/site-packages/distributed/client.py in _gather(self, futures, errors, direct, local_worker)
   1850                             exc = CancelledError(key)
   1851                         else:
-> 1852                             raise exception.with_traceback(traceback)
   1853                         raise exc
   1854                     if errors == "skip":

/home/ubuntu/.local/lib/python3.6/site-packages/datacube/api/core.py in fuse_lazy()

/home/ubuntu/.local/lib/python3.6/site-packages/datacube/api/core.py in _fuse_measurement()

/home/ubuntu/.local/lib/python3.6/site-packages/datacube/storage/_base.py in __init__()

/home/ubuntu/.local/lib/python3.6/site-packages/datacube/model/__init__.py in lookup_measurements()

/home/ubuntu/.local/lib/python3.6/site-packages/datacube/model/__init__.py in _resolve_aliases()

AttributeError: 'DatasetType' object has no attribute '_all_measurements'
```

### Steps to reproduce the behaviour

```python
from dask.distributed import Client
import datacube
import xarray
client = Client('cluster_address')
dc = datacube.Datacube()
query = {
    'lat': (48.15, 48.35),
    'lon': (16.3, 16.5),
    'time': ('2017-01-01', '2020-12-31')
}
data = dc.load(product='product', 
               output_crs='EPSG:32633', 
               resolution=(-10,10),
               dask_chunks={'x': 250, 'y': 250, 'time':20},
                **query)
arr = data.band_1
resampled = arr.resample(time='1w').mean().mean(axis=(1,2))
resampled.compute().plot(size=10)
```

### Environment information

There are some slight mismatches in the versions I hope that these aren't the issue:
```
/opt/conda/envs/datacube/lib/python3.6/site-packages/distributed/client.py:1130: VersionMismatchWarning: Mismatched versions found

+-------------+----------------+---------------+---------------+
| Package     | client         | scheduler     | workers       |
+-------------+----------------+---------------+---------------+
| dask        | 2.27.0         | 2.27.0        | 2.28.0        |
| distributed | 2.27.0         | 2.27.0        | 2.28.0        |
| numpy       | 1.19.1         | 1.19.2        | 1.19.2        |
| python      | 3.6.11.final.0 | 3.6.9.final.0 | 3.6.9.final.0 |
| toolz       | 0.11.1         | 0.10.0        | 0.11.1        |
+-------------+----------------+---------------+---------------+
  warnings.warn(version_module.VersionMismatchWarning(msg[0]["warning"]))
```

* Which ``datacube --version`` are you using? 1.8.3
* What datacube deployment/enviornment are you running against? Jupyterhub running in docker

### LINKED ISSUE #1072: Need the spatial coords to carry correct `spatial_ref` and `crs`
### Expected behaviour
The spatial coordinates `x` and `y` should have correct `spatial_ref` and `crs` after reproject

### Actual behaviour
Only the values are changed but with the old `spatial_ref` and no `crs`. Hence the `results.geobox` crs is wrong.
https://github.com/opendatacube/datacube-core/blob/6ee0462c5de320d820aa4fdd27a4807fe2ab76c2/datacube/virtual/impl.py#L909-L910

### Steps to reproduce the behaviour
N/A

### Environment information

* Which ``datacube --version`` are you using?
  Open Data Cube core, version 1.8.4.dev52+g07bc51a5
* What datacube deployment/enviornment are you running against?
  Sandbox

### PR DESCRIPTION
**Pull request by emmaai**
### Reason for this pull request
-  issue #1072 
- `odc.algo.xr_reproject` crisp clean 

### Proposed changes

- use the implementation `odc.algo.xr_reproject`

 - [x] Closes #1072 
 - [x] Tests added / passed
 - [x] Fully documented, including `docs/about/whats_new.rst` for all changes, note: nothing new, bug fix and better

### CODE REVIEW

**Comment by uchchwhash** [comment]
Issue  #1072 is a serious oversight that I am responsible for, but this solution is unacceptable to me as this package IMHO should not have `odc-tools` as a dependency. Let me see if I can fix it.

**Review by uchchwhash — CHANGES_REQUESTED** [review]
Please do not import `odc.algo`.

**Comment by Kirill888** [comment]
Agree with @uchchwhash `odc.algo` itself depends on `datacube`, we don't want to create dependency loops like that. Probably best to move some of the `odc.algo` code into datacube core and add proper tests for it. Or just fix current code. If one assumes that one time-slice fits into RAM without problems then you CAN have much simpler reprojection logic for Dask arrays and maybe for this application it is best to stick with that approach. Implementation still needs to be correct though.

**Comment by emmaai** [comment]
I'll close the pull request but stay on the branch for a while until #1072 fixed as everybody agrees on

**Comment by snowman2** [comment]
> odc.algo itself depends on datacube, we don't want to create dependency loops like that. Probably best to move some of the odc.algo code into datacube core and add proper tests for it

Here is another alternative: https://github.com/opendatacube/odc-tools/issues/58 :smile:

**Pull request closed without merging**
