### PR TITLE
Set date for release and auto release from travis

### PR DESCRIPTION
**Pull request by omad**
### Proposed changes
- Upload code coverage to [codeclimate](https://codeclimate.com/github/opendatacube/datacube-core) from Travis CI
- Set a release date for the release candidate
- Attempt to upload to PyPI automatically for Tagged Releases from the `stable` branch.

### CODE REVIEW

**Review by jeremyh — APPROVED** [review]
:+1: 

On the auto deployments of `stable` to pypy: Looking at our settings, currently anyone with push access can push to the stable branch. We're reasonably relaxed with giving people push access, so do we want to lock down `stable` a little more, such as requiring a pull request (or only allowing certain users)? At the very least, it could lower the risk of accidents.

**Review by andrewdhicks — APPROVED** [review]

**Comment by omad** [comment]
The `stable` branch does _Require status checks to pass before merging_, which helps, but probably isn't enough. It requires a branch that has been pushed to GitHub to be passing in TravisCI, etc, but it can be **any** branch.

For now I've created another group called [**release managers**](https://github.com/orgs/opendatacube/teams/release-managers) that are the only people can push to stable.

I'm not entirely happy with our git/release workflow. We defined some of it before we'd enforced pull request reviews, which makes the whole process a bit tedious. We're doing something sort of close to `GitFlow` (which I'm not a fan of, see [GitFlow considered harmful](http://endoflineblog.com/gitflow-considered-harmful)), but with different branch names, less strict `feature`/`hotfix`/`release` branch names, and the added complexity of using Pull Requests for merging, and not being strict about `merge -no-ff` and `rebase`.

Would like to see some simplification, but, not sure exactly what to propose yet.

**Comment by jeremyh** [comment]
Agreed on not liking Git Flow.

My understanding of the previous process (which may not reflect what was done) was:
- New code goes to `develop`
- Releases are tagged on develop occasionally
- `stable` always matches the current released tag (and only exists for user convenience, really)

There's no extra merging or anything between the branches. If a patch release is required on an old version (such as `release-1.5`) a dedicated/temporary branch is made from that tag.

(and the branch names `develop` and `stable` are usually preferred because `master` is ambiguous: some git projects use a `master` branch for development, others for stable releases. Better to be explicit with the purpose.)

**Comment by mpaget** [comment]
I'm wading in deep water here but generally speaking I like the discussion of an improved process (which may be more about common practices in our case rather than major process changes, from what I read), and a release managers group.
My understanding after reading the gitflow article and the associated oneflow article is that the ODC process is (or should be?) reasonably similar to http://endoflineblog.com/oneflow-a-git-branching-model-and-workflow#variation-develop-master.

**Comment by omad** [comment]
@mpaget 
Yep, that is pretty close to what we do (and want to do). The major wrinkle which isn't addressed is how to include a code review process, which we're doing with GitHub Pull Requests, and which restrictions are placed on different branches.

**Pull request merged**
