### PR TITLE
Reverting DriverManager and implementing alternatives

### PR DESCRIPTION
**Pull request by omad**
# Reverting `DriverManager` and implementing alternatives

## Reason for Pull Request

Although initially the `DriverManager` code seemed to address the need for extensibility in Data Cube. Upon trying to use it in the NCI/GA deployment we discovered a few show-stopper issues including:

* Passing the `DriverManager` around everywhere broke the distributed bulk processing.
* Database connections were being created unnecessarily in workers which simply needed to load pre-specified data.
* While working with files stored on S3, we ran into conflicts with the S3+Block driver which was registered to handle the `s3://` protocol.

As a result of these, and plenty of diversions on other things, we've had a 6+ month fork between [datacube-core/develop](https://github.com/opendatacube/datacube-core/tree/develop) and [datacube-core/release-1.5](https://github.com/opendatacube/datacube-core/tree/release-1.5) which GA has been maintaining in support of their production environment.

In early December @omad @petewa @rtaib and @Kirill888 discussed some potential solutions. These discussions are documented [in github discussions](https://github.com/orgs/opendatacube/teams/developers/discussions/2) and [in notes from a videoconference meeting](https://docs.google.com/document/d/1l2xOaKyvQRV4h35NELKvyM3DYOUosXJhcj-lgHC8MN4/edit#heading=h.h400fj5rkdxg). Since then @omad and @Kirill888 have been working on implementing the proposed changes.

This Pull Request is our proposed implementation.

## Support for Plug-in drivers

A light weight implementation of a driver loading system has been implemented in [`datacube/drivers/driver_cache.py`](https://github.com/opendatacube/datacube-core/blob/60187e38669d529c55d05a962bd7c5288d906f1b/datacube/drivers/driver_cache.py), which uses [`setuptools` dynamic service and plugin discovery mechanism](http://setuptools.readthedocs.io/en/latest/setuptools.html#dynamic-discovery-of-services-and-plugins) to name and define available drivers. This code caches the available drivers in the current environment, and allows them to be loaded on demand, as well as handling any failures due to missing dependencies or other environment issues.

### Index Plug-ins

**Entry point group:** [`datacube.plugins.index`](https://github.com/opendatacube/datacube-core/blob/9c0ea8923fa5d29dc2a813141ad64daea74c4902/setup.py#L112)

A connection to an `Index` is required to find data in the Data Cube. Already implemented in the `develop` branch was the concept of `environments` which are a named set of configuration parameters used to connect to an `Index`. This PR extends this with an `index_driver` parameter, which specifies the name of the Index Driver to use. If this parameter is missing, it falls back to using the default PostgreSQL Index.

#### Example code to implement an index driver

```python
def index_driver_init():
    return AbstractIndexDriver()

class AbstractIndexDriver(object):
    @staticmethod
    def connect_to_index(config, application_name=None, validate_connection=True):
        return Index.from_config(config, application_name, validate_connection)

```

#### Default Implementation

The default `Index` uses a PostgreSQL database for all storage and retrieval.

#### S3 Extensions

**Implementation**: [`datacube/drivers/s3block_index/index.py`](https://github.com/opendatacube/datacube-core/blob/9c0ea8923fa5d29dc2a813141ad64daea74c4902/datacube/drivers/s3block_index/index.py)

The **S3+Block** driver subclasses the default PostgreSQL Index with support for saving additional data about the size and shape of chunks stored in S3 objects. As such, it implements an identical interface, while overriding the `dataset.add()` method to save the additional data.

### Data Read Plug-ins

**Entry point group:** [`datacube.plugins.io.read`](https://github.com/opendatacube/datacube-core/blob/9c0ea8923fa5d29dc2a813141ad64daea74c4902/setup.py#L104).

Read plug-ins are specified as supporting particular **uri protocols** and **formats**, both of which are fields available on existing `Datasets`

A ReadDriver returns a `DataSource` implementation, which is chosen based on:

- Dataset URI (protocol part, eg: `s3+block://`)
- Dataset format. As stored in the Data Cube `Dataset`.
- Current system settings
- Available IO plugins

If no specific `DataSource` can be found, a default `RasterDatasetDataSource` is returned, which uses `rasterio` to read from the local file system or a network resource.

The `DataSource` maintains the same interface as before, which works at the individual _dataset+time+band_ level for loading data. This is something to be addressed in the future.

#### Example code to implement a reader driver

```python
def init_reader_driver():
    return AbstractReaderDriver()

class AbstractReaderDriver(object):
    def supports(self, protocol: str, fmt: str) -> bool:
        pass
    def new_datasource(self, dataset, band_name) -> DataSource:
        return AbstractDataSource(dataset, band_name)

class AbstractDataSource(object):  # Same interface as before
    ...

```

#### S3 Driver

**URI Protocol:** `s3+block://`
**Dataset Format:** `s3block`
**Implementation location:** [`datacube/drivers/s3/driver.py`](https://github.com/opendatacube/datacube-core/blob/9c0ea8923fa5d29dc2a813141ad64daea74c4902/datacube/drivers/s3/driver.py)

#### Example Pickle Based Driver

Available in `/examples/io_plugin`. Includes an example `setup.py` as well as an example **Read** and **Write** Drivers.

### Data Write Plug-ins

**Entry point group:** [`datacube.plugins.io.write`](https://github.com/opendatacube/datacube-core/blob/9c0ea8923fa5d29dc2a813141ad64daea74c4902/setup.py#L107)

Are selected based on their name. The `storage.driver` field has been added to the ingestion configuration file which specifies the name of the write driver to use. Drivers can specify a list of names that they can be known by, as well as publicly defining their output format, however this information isn't used by the ingester to decide which driver to use. Not specifying a driver counts as an error, there is no default.

At this stage there is no decision on what sort of a public API to expose, but the `write_dataset_to_storage()` method implemented in each driver is the closest we've got. The **ingester** is using it to write data.

#### Example code to implement a writer driver

```python
def init_writer_driver():
    return AbstractWriterDriver()

class AbstractWriterDriver(object):
    @property
    def aliases(self):
        return []  # List of names this writer answers to

    @property
    def format(self):
        return ''  # Format that this writer supports

    def write_dataset_to_storage(self, dataset, filename,
                                 global_attributes=None,
                                 variable_params=None,
                                 storage_config=None,
                                 **kwargs):
        ...
        return {}  # Can return extra metadata to be saved in the index with the dataset

```

#### S3 Writer Driver
**Name:** `s3block`
**Protocol:** `s3+block`
**Format:** `s3block`
**Implementation**: [`datacube/drivers/s3/driver.py`](https://github.com/opendatacube/datacube-core/blob/9c0ea8923fa5d29dc2a813141ad64daea74c4902/datacube/drivers/s3/driver.py#L196)

#### NetCDF Writer Driver
**Name:** `netcdf`, `NetCDF CF`
**Format:** `NetCDF`
**Implementation**: [`datacube/drivers/netcdf/driver.py`](https://github.com/opendatacube/datacube-core/blob/d7ccf1b01ccfee1dec00a1c444e641ae79586191/datacube/drivers/netcdf/driver.py#L33)

### Removed 3D Ingestion feature

We've decided to revert the changes to `datacube ingest` which were added to support ingesting to a 3D chunk in S3. We know this is an essential feature for the S3 Block storage system, but would prefer it to be implemented as a separate command. Our issue is that it doesn't support incremental update of datasets when they have been added or changed.

Being able to incrementally add or change datasets and then ingest them is vital for the NCI/GA implementation of Data Cube. This is the reason we have separate tools for **ingest** (which deals with a single dataset at a single time, and so works fine with incremental updates) and **stack** which is responsible for taking a period of time and re-storing it in deep-time storage units.

Being able to update storage blocks involves all sorts of thorny issues, and the simple implementation didn't address any of them, which could lead to confusion.

### Protocol name change from `s3://`
We have renamed the protocol used for the s3 driver to `s3+block://`.

We're starting to use files stored in s3, which is supported by many tools out of the box using the standard `s3://` protocol name.

### Changes when specifying the environment 
Added `index_driver` parameter

### Change to Ingestion Configuration
Must now specify the **Write Driver** to use. For s3 ingestion there was a top level `container` specified, which has been renamed and moved under `storage`. The entire `storage` section is passed through to the **Write Driver**, so drivers requiring other configuration can include them here. eg:

```yaml
...
storage:
  ...
  driver: s3block
  bucket: my_s3_bucket
...
```

# References and History

* [Pluggable Back Ends Discussion [7 December 2017]](https://github.com/orgs/opendatacube/teams/developers/discussions/2)
* Teleconference with @omad @petewa @rtaib @Kirill888 on _12 December 2017_.
* [Notes from ODC Storage and Index Driver Meeting](https://docs.google.com/document/d/1l2xOaKyvQRV4h35NELKvyM3DYOUosXJhcj-lgHC8MN4/edit#heading=h.h400fj5rkdxg)

### CODE REVIEW

**Comment by petewa** [comment]
Hi @omad and @Kirill888,

Thank you both for your hard work on this pull request.

Ideally I want to knock this item out of the way asap, so it's not a blocker for the ODC community.

I'm afraid we won't have time to have a look at this until after January at least, maybe after February.
We got some hard deadlines coming up, one in January and one in February that both @rtaib and I are working on.

We'll try our best to get on this one asap.

I had a look a week or two ago, and the changes were workable at first glance.

I suspect most of the changes will be workable, except maybe the removal of 3D Ingestion.
We actually do not use 3D ingestion for the S3 driver currently due the the way Data Cube retrieves data. I suspect it will hurt S3 driver performance (similarly for the NetCDF driver) if we use it currently.
I suspect it will increase performance for S3 and NetCDF driver when we move Data Cube to nD block reads especially for temporally deep analysis.

We'll have a deeper look, code wise + testing when we can.

Is this workable for you?

Kind Regards,
Peter

**Comment by mpaget** [comment]
This probably isn't the forum for such a discussion (apologies). Nevertheless I just wanted to raise it while its 'on topic' so that we remember to discuss this when the "as is" architecture docs and virtual-products proposal are shared in the coming weeks.

How do I say this ... it seems to me on the face of it that there is commonality in goals between 3D ingestion (as described by Peter; I've left this pull request to you folks) and the virtual-products proposal where @Kirill888 says "it helps generalise a) build 3d VRT (virtual raster) and b) load that VRT into memory" (paraphrased).

So, on one hand it seems that you're proposing to remove 3D data reads (this pull request), and replace it with 3D virtual combinations after 2D reads (virtual-products). I appreciate that the 2D scenario is largely a response to "as is" core code, which is fine. But, if the above is true-ish, wouldn't it be better to direct some of the virtual-products effort to helping the more generic 3D reads topic?

And thank you very much for all the development work in pulling this pull request together. Its a monster, and I suspect at times created corresponding headaches which you evidently navigated through. Well done.

**Comment by Kirill888** [comment]
@mpaget @petewa The only thing we removed is 3D ingestion, as in combining 2D ingest with stacking in one step. Reasons for this removal were outlined by @omad in the pull request. Basically incremental ingestion in the presence of stacking is poorly defined. Nothing stops anyone implementing a version of ingest+stack in one step, it just should not happen in the `datacube ingest` command, not until incremental ingestion for this configuration is implemented in a robust fashion.

"Virtual products" have nothing todo with the changes in this pull request. 3d raster building already exists, but constrained to just loading data from one product without any transform. Virtual products are meant to generalise VRT to include more products than one and to incorporate on-the-fly processing that can happen one time slice at a time.

3D data **reads** can not be removed, because they don't exist. The abstraction for reader is per timeslice per band, nothing in this pull request changes that.

If you have 3D reads from S3 storage, great, nothing should be affected, I assume you are doing it outside of `dc.load` since abstraction within `dc.load` is to read one timeslice for one band, and I haven't seen any changes in any branch that attempt to change this behaviour. You will need to re-create 3D ingest by copying old code into a standalone app, as a quick work-around you can use `datacube ingest` from an older checkout to ingest your data and continue working on read/execute in the develop branch.

**Comment by petewa** [comment]
Update on the pull request for record keeping sake.

These errors exist (I can see that these are in the process of being fixed, thanks @Kirill888):
1.  
  SKIP [1] /home/travis/build/opendatacube/datacube-core/tests/test_driver.py:15: could not import 'datacube.drivers.s3.driver.s3lio'
  SKIP [1] /home/travis/build/opendatacube/datacube-core/tests/test_driver.py:50: could not import 'datacube.drivers.s3.driver.s3lio'

2.  
  XFAIL integration_tests/test_full_ingestion.py::test_s3_full_ingestion[US/Pacific-s3block_env]
  XFAIL integration_tests/test_full_ingestion.py::test_s3_full_ingestion[UTC-s3block_env]

  This should be using the s3-test driver for testing.

There is a change to tests/drivers/test_s3_storage.py changing the tests from multi-process to single-threaded. I'll catch up with Damien when he's back.

**Comment by Kirill888** [comment]
1 and 2 were fixed today.

1. Was a bad import guard (I guess modules moved location, or were typed in wrong from the start)
2. Was using the correct driver for ingestion from the start, but loading data was not succeeding because there were no test driver for reading so the code tried to load from actual S3, after adding test driver for reading side things started to work.

**Comment by petewa** [comment]
After taking a deeper look at the PR, we must say again. Great Job guys!
It's good to see that ODC now has a proper plugin mechanism.

## Issues this PR solved for us:
* Proper plugin mechanism.
* Pickling metadata for load was failing on Python 2.
* Unnecessary database connections during data load.
* A learning exercise on how to better work in the ODC code base. To be discussed at the ODC Workshop.

**Note:** The list may look lengthy and time-consuming. We have provided possible solutions to make this easier.

## Issues to be resolved:

**1. Multiproc ingest fails for s3/s3test**

**Error:**
```pytb
2018-02-05 04:50:48,972 8840 agdc-ingest INFO Submitting task: (8, -21, numpy.datetime64('1990-03-02T23:11:16.000000000'))
Traceback (most recent call last):
File "/home/ubuntu/anaconda3/envs/g36/lib/python3.6/multiprocessing/queues.py", line 234, in _feed
	    obj = _ForkingPickler.dumps(obj)
	  File "/home/ubuntu/anaconda3/envs/g36/lib/python3.6/multiprocessing/reduction.py", line 51, in dumps
	    cls(buf, protocol).dump(obj)
	TypeError: can't pickle _thread.RLock objects
```
**Solution:** Fixed by cloudpickling/dill `driver` in `datacube/scripts/ingest.py`
```python
def ingest_work(config, driver, source_type, output_type, tile, tile_index):
    # pylint: disable=too-many-locals
    _LOG.info('Starting task %s', tile_index)
    from cloudpickle import loads
    driver = loads(driver)
```
```python
def process_tasks(index, config, driver, source_type, output_type, tasks, queue_size, executor):
# pylint: disable=too-many-locals

def submit_task(task):
    _LOG.info('Submitting task: %s', task['tile_index'])
    from cloudpickle import dumps
    return executor.submit(ingest_work,
                           config=config,
                           driver=dumps(driver),
                           source_type=source_type,
                           output_type=output_type,
                           **task)
```
**2. `dataset_location.uri_scheme` is always set to `file` in the database regardless of index/driver used and environment set which causes errors on load.**

**Solution - Part 1:**
Set dataset_location.uri_scheme to the index specified in datacube environement.
```python
class DatasetResource(BaseDatasetResource):
    """The s3 dataset resource extends the postgres one by writing
    additional s3 information to specific tables.
    """

    def __init__(self, db, dataset_type_resource, uri_scheme='s3+block'):
        """Initialise the data resource."""
        super(DatasetResource, self).__init__(db, dataset_type_resource)
        self.uri_scheme = uri_scheme

    def add(self, dataset, sources_policy='verify', **kwargs):

        dataset.uris = ['%s:%s' % (self.uri_scheme, uri.split(':', 1)[1]) for uri in dataset.uris] \
           if dataset.uris else []
```
This works but cumbersome:
```bash
# change env to s3block which uses the s3block index
$ datacube -v system init

# change env to default index which uses the default index
$ datacube product add docs/config_samples/dataset_types/ls5_scenes.yaml
$ datacube dataset add --auto-match /home/ubuntu/data/LS5/*

# change env to s3block which uses the s3block index
$ datacube -v ingest -c ../ls5_pq_albers_s3.yaml --executor multiproc 8
$ datacube -v ingest -c ../ls5_nbar_albers_s3.yaml --executor multiproc 8
```
**Solution - Part 2:**
Use default datacube index during indexing.
```
@pass_default_index to indexing or @pass_index(env='datacube') - requires code change
```
```bash
# change env to s3block which uses the s3block index
datacube -v system init

datacube product add docs/config_samples/dataset_types/ls5_scenes.yaml
datacube dataset add --auto-match /home/ubuntu/data/LS5/*

datacube -v ingest -c ../ls5_pq_albers_s3.yaml --executor multiproc 8
datacube -v ingest -c ../ls5_nbar_albers_s3.yaml --executor multiproc 8
```
This works as before.

**3. `location` field missing from `docs/config_sames/ingester/ls5_nbar_albers_s3test.yaml` causing ingest to fail.**

**4. `config.py::38` has a `[user]` section but doesn't seem to be used. It looks like `default_environment: datacube` should be used to specify the default environment but does not appear functional.**

**Workaround:** `export DATACUBE_ENVIRONMENT=s3block_env`
**Solution:** Implement `[user] default_environment=<env>`

**5. Revert `datacube/drivers/s3/datasource.py` to use `get_data_unlabeled_mp` instead of `get_data_unlabeled`**

**6. SharedArray should use `shm` instead of `file` on linux for now**

**Reason:** Defer usage of `file` for linux until further testing/benchmarks.
**Solution:** use `shm` for linux and `file` for other os including mac. 

**7. There should be a `NetcdfReaderDriver` for consistency.**

**8. `datacube/drivers/netcdf/driver.py` should have a `PROTOCOL` field for consistency.**

e.g. `file` or `s3` or `http`

**9. `datacube/drivers/s3/driver.py`**

* s3 driver protocol should be `s3+aio`. This should really be just `s3`, for discussion during the ODC workshop.
* s3 driver format should be `aio`
* s3-test driver protocol should be `file+aio`
* s3-test driver format should be `aio`
* rename where `s3block`/`s3+block` is mentioned.

**Note:** I apologise, I said I would do this one. I spent the time investigating and finding solutions to the first 2 errors above.

**10. `docs/config_samples/ingester/ls5_nbar_albers_s3test.yaml` and `docs/config_samples/ingester/ls5_pq_albers_s3test.yaml` should have `tile_size` set to `(200000, 200000)`**

If different parameters are required for tests, it's better to duplicate the file with different parameters and including them in the test directory.

`docs/config_samples` are intended for users to grab configs with known good values as a good starting point.

## Minor:
**1. Remove `datacube/drivers/s3block_index/_schema.py` as it seems unused.**

**2. `location` in ingest yaml should be moved under storage similar to bucket as it is driver dependent.**

Storage driver dependent parameters should be in its own section.

**3. `config.py::26` `default` should be uppercase `DEFAULT` to match line 30 `[DEFAULT]`. The `configparser` docs say that "By default, section names are case sensitive but keys are not"**

**4. Currently every read/write driver is loaded when the rdr_cache/writer_cache is loaded and possible heavy driver initialisation may be performed for drivers that may not even be used in the future**

There are many solutions to this:
* Upfront loading - preload drivers specific to environment on datacube initialisation
* On-demand loading - load only required driver specific to the load request. e.g. load only the `s3+aio` read driver only when a `s3+aio` load is called and not load all read drivers.
* Two stage loading:
  - one for getting the `PROTOCOL` / `FORMAT` that doesn't call the `init()` - only gets metadata
  - one for actual load that does call the `init()` and initialises the driver

**5. `core.py::562` silently disables `use_threads` if the required modules are not present. A warning should be displayed.**

This was part of the original PR but should be addressed at some point. Be nice to make it part of this merge

**6. Make environment names consistent. i.e. all with the `_env` suffix, or without it.**

e.g. `integration_tests/test_full_ingestion.py::40` and `datacube/config.py`

## Suggestions post-PR: (This would be a team ODC effort)

**1. Index + Storage (Read/Write) module and interface** To be discussed at ODC Workshop

**2. Plugin Architecture.** To be discussed at ODC Workshop

* I want my datacube to be built with plugin a, b, c, d, e.
* Datacube default plugin is a standalone plugin.
* datacube-core only defines a list of module interfaces, plugin manager + bootstrap code.
* Plugins modules live in their own repository external to datacube-core similar to Brian K's original repository structure suggestion.

**3. nD ingest + nD block reads to be revisited at a later date.**

**4. Refined driver testing**  To be discussed at ODC Workshop

* testing of drivers defined in setup.py::entry_points on basic ingestion/retrieval tasks
* file based test driver for testing all code up until storage io

**5. Proper S3 tests** To be discussed at ODC Workshop

**6. `datacube/drivers/readers.py::71, 24` and `datacube/drivers/writers.py::52, 15`. The reason for use of the `__call__` method is not clear when a normal method such as `find_driver` could have been used and may improve legibility/maintenance.**

Thank You,
Peter, Ronnie

**Comment by Kirill888** [comment]
Major issues have now been resolved as far as I can tell.


## re Minor.2: ingest `location` parameter

Ingest is very much file based NetCDF producing app, it's a miracle it can work at all with the new plugin infrastructure. Proper support for ingesting to non-file locations needs more thought. Can be addressed after merge.


## re Minor.3: default environment name

Yes it's an error, but it's an error that enables backwards compatibility with
previous `[datacube]` config. This should be addressed in a separate PR.

## re Minor.4: lazy loading drivers

- Users have an option of not installing drivers they won't care about using
- Plugin driver writers already have an option of lazy initialization internally
- Driver cache is itself lazy loaded, so things like `datacube --help` should not need to pay the cost of loading all the drivers
- If you don't write data, writer drivers should not be loaded


## re Minor 5 and 6

Can wait til after merge.

**Review by petewa — APPROVED** [review]
Great work!

We can discuss the loose ends during the ODC workshop.

**Pull request merged**
