### PR TITLE
Let SimpleDocNav.id property return UUID, to improve lineage resolution

### LINKED ISSUE #1300: Doc2Dataset fails if lineage sources are specified as UUIDs rather than strings
Converting an input doc that contains lineage references to a Dataset (using `Doc2Dataset(index, fail_on_missing_lineage=True, verify_lineage=False, skip_lineage=False)`) fails if the lineage references in the input doc are of type `UUID` instead of `str`.

In [dataset_resolver, hl.py around line 174](https://github.com/opendatacube/datacube-core/blob/c5486c854dc4fe3e1bef670a5ce01010d0caa938/datacube/index/hl.py#L174), the identifiers of the resolved lineage sources are converted to strings. Then, missing lineage items are determined by subtracting the resolved identifiers from the input set of lineage sources. But if the input references are of type `UUID`, this simple set subtraction is incorrect, and as a result the lineage items will be considered missing: 
```python
        db_dss = {str(ds.id): ds for ds in index.datasets.bulk_get(all_uuid)}

        lineage_uuids = set(filter(lambda x: x != main_uuid, all_uuid))
        missing_lineage = lineage_uuids - set(db_dss)
```
(After that, also generating the error message in line 180 fails, because it expects missing_lineage items to be strings).

In practice, it is very likely that lineage source identifiers will be of type `UUID`, given that the `Dataset` class uses `UUID`s for identifiers, as do external interfaces like e.g. `eodatasets3.DatasetPrepare.note_source_datasets()`.
Before doing the subtraction, both lineage_uuids and db_dss sets should be normalized to contain a single datatype.

### PR DESCRIPTION
**Pull request by tijmenr**
### Reason for this pull request

Fix issue #1300 [Doc2Dataset fails if lineage sources are specified as UUIDs rather than strings](https://github.com/opendatacube/datacube-core/issues/1300#)

### Proposed changes

- Let SimpleDocNav.id property return a UUID (instead of a string)

 - [X] Closes #1300
 - [X] Tests passed
 - [ ] Fully documented, including `docs/about/whats_new.rst` for all changes

### CODE REVIEW

**Comment by Kirill888** [comment]
Thanks for the PR @tijmenr, I wonder if it would be more proper to instead change the other way? 

https://github.com/opendatacube/datacube-core/blob/5456533119d245a35fee33f00486fa50fc67f5d2/datacube/utils/documents.py#L387-L389

As in, force conversion to `UUID|None` in the `SimpleDocNav` class as it seems that other code assumes UUID coming out of it judging by the type annotations, I think that might result in a smaller change and is probably a more proper way to address the mismatch of types in `hl.py`

**Comment by SpacemanPaul** [comment]
I agree that Kirill's suggested approach is cleaner and simpler (and also has less messy interaction with other refactoring work I have underway.

**Comment by tijmenr** [comment]
Using UUID is indeed cleaner. I went for strings in my PR instead because it seemed to have less chance of breaking other stuff, but I hadn't noticed that simple way to ensure UUIDs via SimpleDocNav.

**Comment by tijmenr** [comment]
Updated the PR, now using UUIDs instead of strings. 

Note: This required changes in quite a few places, especially in unit/integration tests, where the assumption was that id's are strings.

**Pull request closed without merging**
