### PR TITLE
Measurements 500

### LINKED ISSUE #500: Proposal: Extend Measurements class to add base_attrs method
What are your thoughts on extending the [Measurements class](https://github.com/opendatacube/datacube-core/blob/develop/datacube/model/__init__.py#L314-L328) to have a `base_attrs()` method that could replace functionality [here](https://github.com/opendatacube/datacube-core/blob/develop/datacube/api/core.py#L443-L454)?

Then, it could be dropped in the [measurements property](https://github.com/opendatacube/datacube-core/blob/develop/datacube/model/__init__.py#L414-L420) of the DatasetType.

### PR DESCRIPTION
**Pull request by snowman2**
### Reason for this pull request

In order to be able to add/remove custom attributes on load (ex. description), having the filter functionality for what's included in the `datacube.model.Measurement` class makes that process easier for downstream applications.

### Proposed changes

- Use the `datacube.model.Measurement` class to generate attributes when loading in files.
- Update the `datacube.model.Measurement` class to inherit from `dict` to preserve current behavior.

 - [x] Closes #500
 - [x] Tests added (not necessary in this case as existing behavior should not change) / passed 
 - [x] Fully documented, including `docs/about/whats_new.rst` for all changes

### CODE REVIEW

**Comment by uchchwhash** [comment]
Hi @snowman2, @alfredoahds,

Thanks for the pull request. Before we delve any deeper into this issue, I would like to make sure that I understand the problem you are trying to solve.

Currently, the `datacube.model.Measurement` class isn't actually being used by the ODC code at all. The measurement (or band) information being passed around between the `datacube.Datacube` methods are just plain dictionaries. So your custom index can add the additional information that you want to attach as extra items into those dictionaries and hopefully nothing should break.

My understanding is (please correct me if I am wrong) that you want these extra information to be available as attributes of the loaded `xarray.DataArray`s. In that case what we would need to do [here](https://github.com/opendatacube/datacube-core/blob/0e4fe679dd7b72c7cb35ae3e32ce94bcb8b22de8/datacube/api/core.py#L443-L454) is instead of specifying what we think should be copied, we need to specify what we need to filter out (in this case, the `name` and the `dtype`) (and additionally attach the `crs` as an exceptional case).

Let us know if that's what you are after.

**Comment by snowman2** [comment]
@uchchwhash, you understand the problem correctly. So, if you modify the logic to filtering out attributes `name` and `dtype` and attach the `crs`, then we should be able to do what we need to do.

Currently the `datacube.model.Measurement` class inherits from dict, so it is mostly there to filter attributes and ensure required attributes exist. If you want to use the `datacube.model.Measurement` class as shown in this PR, then maybe we could add a `attrs()` method that would return the filtered attributes.

**Comment by snowman2** [comment]
@uchchwhash, I see now that adding the attributes method will impact users passing in a regular dictionary. I will try another iteration.

**Comment by alfredoahds** [comment]
Hey @uchchwhash,

Our main intention is to be able to automatically add arbitrary attributes to the Datacube created datasets based only on model attributes without having to overwrite or update the `create_storage` method. The main benefit of having a model method that handles the formatting of the dictionary is to allow for some preprocessing-like functionality where we can make additional modifications to the DataArray attributes at will prior to Dataset creation (without overriding `dict.items` on the measurement class). Our pilot use case is just to add a few additional fields for raster datasets, but having the ability to customize measurement attributes will be useful for some of the vector dataset interoperability work we've been doing. 

I think Alan's latest changes handle your concerns (edit: before commit ae76296) and result in a comparable output to the current state, but puts us in a bit of the same place where we'd need to update the `create_storage` method again in the future for other 'custom'/non-standard additions. I'm not too sure how many users are interacting with the API at a low enough level to be effected by switching over to using the `datacube.model.Measurement` class as that's usually managed through via the `DatasetType`, but would you all be opposed to moving in that direction? Assuming it's a full changeover to using the class over standard dicts, and the integration tests still pass?

**Comment by uchchwhash** [comment]
Hi @snowman2, @alfredoahds,
Thanks for the detailed explanation. I think I understand the purpose better now. It would be nice to have some cosmetic issues addressed before we merge it though, let me know if you don't think they help. In case you don't have any objections against them, I can also address them after the merge.
- Rename the `attrs` method to `dataarray_attrs` or `dataarray_attributes` to make its use-case clearer.
- Keep `OPTIONAL_KEYS` around (and enforce it). If we don't know what keys we are anticipating, we might as well use `dict`s. Your derived class can then override it with its optional keys. 
- We ditched Python 2 compatibility. Just `super()` should work instead of `super(Measurement, self)`.
- `copy` quite possibly does not add too much at this point.

Let us know what you think. We appreciate you taking the time to make sure the builds are passing!

**Comment by snowman2** [comment]
@uchchwhash, that sounds good. I made the changes you requested. I would love to remove the copy method, however it is required as the super class `dict` method returns a regular dictionary and does not preserve Measurement class with the `dataarray_attrs` method. I would have used `collections.UserDict`, however it fails the validation tests as the UserDict is not of type `object`.

**Review by omad — APPROVED** [review]
Looks good to me!

Thanks for the productive discussions everyone.

**Comment by uchchwhash** [comment]
That's awesome! Thanks @snowman2!

**Pull request merged**
