### PR TITLE
Compatibility with Colab

### PR DESCRIPTION
**Pull request by sebasmos**
### Reason for this pull request

Running datacube on Colab might be useful for other users
...

### Proposed changes

Suggested libraries and packages are on README.rst

- 
- 

 - [ ] Closes #xxxx
 - [ ] Tests added / passed
 - [ ] Fully documented, including `docs/about/whats_new.rst` for all changes

### CODE REVIEW

**Comment by Kirill888** [comment]
@sebasmos thanks for this. Your PR includes a backup version of README, `readme.rst~` file. How comfortable are you with git, would you be able to rebase your PR as a single commit without `readme.rst~` in it?

Can you also add a bit more detail, like a single paragraph as to what is this for and high level explanation of what your sample script does

**Comment by sebasmos** [comment]
Sure, I have just updated the branch "develop" with these changes.

**Comment by sebasmos** [comment]
I added a paragrapth with more details about how to import datacube on Google Colab within a single cell. I am currently working with it on this way, that is why I thought it would be useful for other users.

**Review by RichardScottOZ — COMMENTED** [review]
Maybe:-

The following script allows reproducing the  ``datacube`` library on Google Colaboratory. As this is currently working in a conda environment, individual libraries and corresponding dependencies must be installed independently. For reproducibility on Colab, execute the following commands in a single cell.

**Comment by sebasmos** [comment]
You are right! I've added the corrections.

**Comment by alexgleith** [comment]
I think you might want to point to the example code (outside this repo) that you can use to actually use ODC on Collab. Bootstrapping the DB and whatnot.

Somewhat unrelated, I think the way you overload `dc.load` should be replicated in `dc.find_datasets` so that both functions behave as expected :-)

**Comment by alexgleith** [comment]
I'm not sure this is the right place for these docs. Please re-open if you disagree :-)

**Pull request closed without merging**
