### PR TITLE
remove direct osgeo dependency

### PR DESCRIPTION
**Pull request by uchchwhash**
### Reason for this pull request
Following @Kirill888's suggestions, this PR migrates our geometry and CRS code to use `shapely` and `pyproj` instead of `osgeo.ogr` and `osgeo.osr` respectively. We found `osgeo` library (Python bindings to the GDAL library) not to be highly portable. We will be relying on `rasterio` to pull in GDAL instead.

Big thanks to @andrewdhicks and @whatnick for invaluable pointers.

**NOTE**: I expect downstream code that depends on the `osgeo` backend to break. The severity of the consequences of these changes is unclear to me. IMO this should not go into Release 1.8 which I would like to get out as soon as possible. Other than that this PR is essentially good to go.

### Proposed changes
- Migrate to `shapely` and `pyproj`
- Update the NetCDF writer code to make use of the `to_cf()` method from `pyproj.CRS`
- Remove a couple of obscure CRS tests
- Remove the `galsprepare.py` script that an integration test depended on, it now uses the output of the script directly instead

- [X] Closes Issue #867

### CODE REVIEW

**Comment by snowman2** [comment]
I would recommend pinning pyproj>=2.5 if using the to/from_cf stuff as it was updated to be WKT based & has all grid mapping parameters. See:https://github.com/pyproj4/pyproj/pull/534

**Comment by snowman2** [comment]
Also, this may be useful: https://github.com/corteva/rioxarray/pull/93

https://github.com/corteva/rioxarray/blob/0e5492646b6c0b9d0fad603d99eb38e0169e44d4/rioxarray/crs.py#L11-L35

**Comment by Kirill888** [comment]
@snowman2 thanks for the hint. We were thinking of delaying this until after 1.8 release though, since it's such a major change and it is likely to impact external code as well and we haven't tested it in production yet. It is not "just an experiment" though, we will go through with it, just not for the upcoming release.

**Comment by snowman2** [comment]
> We were thinking of delaying this until after 1.8 release though

We are looking forward to this change - it will be nice to not have to install the `osgeo` python wrapper anymore. Sounds like more testing is needed - and I don't disagree that it would be safer to do so before releasing. We may run some tests on our internal code using this branch and report any issues found.

**Comment by snowman2** [comment]
No issues transitioning on our end using the code.

We made sure to add this though:
```python       
            from rasterio import __gdal_version__
            if LooseVersion(__gdal_version__) < LooseVersion("3.0.0"):
                return self.to_wkt("WKT1_GDAL")
            return self.to_wkt()
```

**Comment by Kirill888** [comment]
Thanks for testing this @snowman2. So this change is for interop with pre-compiled `rasterio` in `.wkt` property?

**Comment by Kirill888** [comment]
@uchchwhash if you have time for this, can you test this branch in au-sandbox with dea-notebooks? That's probably the largest test-suite outside of core we have access to.

**Comment by snowman2** [comment]
@Kirill888, the change was added because you can have GDAL 2 for rasterio and pyproj wheels. The default WKT version for pyproj is version 2, and that doesn't work with GDAL 2.

**Comment by uchchwhash** [comment]
Thanks @snowman2 for your awesome work!

@Kirill888 sounds great, will do.

**Review by Kirill888 — APPROVED** [review]

**Comment by Kirill888** [comment]
@snowman2 we decided to include this change into upcoming 1.8 release, so `datacube` in `develop` branch no longer depends on `gdal` python bindings. There is also a beta release on PyPI, you can try if you would like:

```
datacube[s3,performance]==1.8.0b6
```
above also includes support for NetCDF/CF convention.

**Comment by snowman2** [comment]
@Kirill888 I am glad to hear that it made it into 1.8 :tada:. I will try out the new version with out internal code when I get a moment.

I tested out release 1.8.0b5 a while back on the `geocube` package and it all worked (needed some tweaks because I was using an attribute prefixed with `_` :smile: ):
https://github.com/corteva/geocube/pull/24

**Comment by snowman2** [comment]
@Kirill888 all tests pass on our internal code as well.

**Pull request merged**
