### PR TITLE
Cleaning up unused code from gdf trial

### PR DESCRIPTION
**Pull request by v0lat1le**

### CODE REVIEW

**Comment by simonaoliver** [comment]
Representing minimal build components as they mature

**Comment by woodcockr** [comment]
Rejection - vote from me. This pull request is removing some code that I believe is still in use in the Analytics and Execution engine development. I suggest consulting with them in preparation of a revised pull request to prevent down stream development issues.

**Comment by petewa** [comment]
This can't be accepted.
The Analytics Engine, Execution Engine and ND Expression Language is part of the minimum build.
This was presented yesterday at the minimum build presentation & review, and is still under ongoing development.

I also suggest the GDF remain until the new Data Access API reaches the functionality of the GDF.

I vote -1.

**Comment by v0lat1le** [comment]
When I offered to port Analytics Engine and Execution Engine from GDF to minimal build branch Peter said he wasn't going to use that code

**Comment by v0lat1le** [comment]
@petewa in datacube/gdf.py there are get_descriptor and get_data functions, so I believe Data Access API has reached the functionality of GDF (given the absence of the specification of said functionality).

**Comment by v0lat1le** [comment]
When AE and EE are ready to be integrated the code can be added to the current release at that time. We're use revision control, so it's not like the GDF trial code is gone forever

**Comment by simonaoliver** [comment]
Sounds reasonable to me. Minimal build releases could be staged over the coming weeks (prior to wrapup of minmimal build by xmas) and include AE/EE/QL components as they become functional against the storage access. For GDF trial components that have been superseded it seems to make sense to remove these from the minimal build branch.

**Comment by jeremyh** [comment]
My understanding is that by the end of milestone 1 everything will be under the `datacube` package instead of `gdf`. 

Any code that uses the `gdf` packages wont work in this branch already, as those packages depend on the old schema and NetCDF structures.

The code in the `datacube` package may be insufficient at the moment for AE/EL functionality, but that's ok (it's far from being the only missing functionality). We plan to add it, and merge the AE/EL code into this branch (and the `datacube` package) by the end of the milestone.

(In either case, I can't think of any reason we would end the milestone with AE/EL code still using `gdf` packages, so this isn't blocking AE/EL from being in the milestone.)

+1 from me.

**Comment by woodcockr** [comment]
Removal of in progress code will mean references made to this branch and this code in yesterday's review will no longer be valid. It also disregards the committed development effort that is underway and a suggests no progress is being made on the other components.
Since the two modules under development for the minimal build are in two different branches (from what I can tell) I suggest the creation of a combined branch containing all of the minimal build components in progress and then the removal of truly deprecated code. This would then have the two development teams involved working off the same code base rather than this rather awkward independent branch which is not the full minimal build as its name seems to indicate and only contains one set of activities.

How does that sound?

**Comment by jeremyh** [comment]
Good points Rob. 

Since `develop` is not being used otherwise, could we merge `ga/milestone1` into develop and make it the primary point of milestone1 development instead? We can leave `ga/milestone1` as-is to stay relevant to the status as-of the presentation if needed.

Having separate feature branches is not itself unusual in this milestone though. A few weeks ago there were four separate, fully independent and incompatible branches for my, Greg, Damien and Peter's modules, and we're gradually merging them one-by-one into here, fixing the incompatible interfaces as we go. We're still creating separate branches for larger and in-progress features as needed (my new query code was separate earlier this week, and Damien now has a new one).

**Comment by petewa** [comment]
@v0lat1le the original AE/EE from the GDF trial and Expression Language was presented at the minimum build presentation & review and is part of the minimum build.
I am not sure which code you are referring to but in this pull request, the AA/EE and EL have been removed.

@v0lat1le the spec for the the get_descriptor and get_data functions for EDA are here: http://www.datacube.org.au/wiki/Data_Access_Interface
This is a subset of the get_descriptor and get_data functionality from the GDF trial that is required for the EDA use case.
For the full functionality of the get_descriptor and get_data as per the GDF trial please see:
https://github.com/data-cube/agdc-v2/blob/master/gdf/__init__.py.
It has examples of the inputs and outputs of each function.
As we discussed, the returned ndarrays need to be an Xray DataArray.
You can also reverse engineer the code if it will help you.

I still need the GDF code for testing until the Data Access API supports the functionality of the GDF. Once I can confirm this and am happy with the Data Access API, then the GDF can go.

@v0lat1le I have been invited to the meeting that you are having with the author of the GDF to understand the functionality of get_descriptor and get_data later this week.

I suggest we take this offline and discuss it as a coherent development team and follow up on @woodcockr 's suggestions on bringing these branches together.

**Comment by v0lat1le** [comment]
@petewa you have commit access to the repository. Please collaborate with us and move the code that you require into the datacube package

**Comment by woodcockr** [comment]
@jeremyh your suggested use of develop would be consistent with common practices and would make it simple to move these branches together given the dev branches both come from there. I'd be keen to see that happen. The point your raise about the use of feature branches is important. It seems to me at least that this particular branch has strayed beyond its intended scope to include changes in AE which are impacting other development teams. Best to work with in the scope, and push to develop than have AE bring its piece in once the Storage Access API is resolved. We could also replace the additional analytics done without the AE module with an AE enabled one in the process and bring all the dev back into unification as discussed when working on the review presentation content.

**Pull request closed without merging**
